### ISSUE TITLE
Garnet server.py needs to be a daemon but there needs to be the option of it being run interactively

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/insite#24]
server.py helps with developer troubleshooting but it doesn't make garnet a functional production system. It will need to be converted to a daemon.

This daemon needs to be automatically started as part of the installation process.

Use infoset-ng api daemon as a guide.

**Comment by Pr0x1m4** [comment]
Project structure has changed, daemon functionality has been moved to [system-server](https://github.com/Pr0x1m4/system-server). Closing.
