### ISSUE TITLE
Implement Settings/Configuration page

### ISSUE THREAD

**Issue by Pr0x1m4** [PalisadoesFoundation/insite#33]
A web UI is need to configure and validate settings found in [config.yaml](https://github.com/PalisadoesFoundation/garnet/blob/master/etc/config.yaml)

See proposed design of Settings page
![untitled drawing 2](https://cloud.githubusercontent.com/assets/4820517/26525529/74254e04-431f-11e7-8fdc-66edd49d282b.png)

**Comment by Pr0x1m4** [comment]
@Mardii-D-King

**Comment by Mardii-D-King** [comment]
@Pr0x1m4 Looks like a basic data entry page, seems simple enough.

**Comment by Pr0x1m4** [comment]
Keep in mind that each field has to be validated before the user can write the changes. For example

If the user enters a file path, garnet should check it that file exists before the changes are saved, similarly for the rest of the fields.

**Comment by Pr0x1m4** [comment]
What is the status on this @Mardii-D-King ? Post a screenshot of your progress

**Comment by Mardii-D-King** [comment]
I have so far added a settings tab to the navbar and create a Settings components where i will be adding the form.

**Comment by Mardii-D-King** [comment]
![2017-05-29-134820_1366x768_escrotum](https://cloud.githubusercontent.com/assets/11225020/26560642/e0085a42-44a7-11e7-9238-d55b00e47a01.png)

Above is Screenshot of the Settings page in progress.

**Comment by Pr0x1m4** [comment]
Latest removal of `react-bootstrap` broke settings page. It needs to be adjusted with `grid-styled`
![2017-08-24-121358_3840x2160_scrot](https://user-images.githubusercontent.com/4820517/29679177-b64bfc64-88c6-11e7-9e1a-ab146abb4e4c.png)

**Comment by Pr0x1m4** [comment]
In light of [collectr](https://github.com/PalisadoesFoundation/collectr.git) being made into it's own repository, it might be appropriate to discard the `Settings` page altogether

**Comment by Mardii-D-King** [comment]
So all that would be shown on garnet are the graphs and agents

**Comment by Pr0x1m4** [comment]
Stale issue. Closing
