### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by Maradox-D-Krypt** [PalisadoesFoundation/insite#40]
Choose one: is this a bug report or feature request?

The Dockerfile and docker-compose file should be removed since it is no longer required in the project as well as the www folder.

### Input Code

```js
var your => (code) => here;
```

### Garnet Configuration (etc/config.yaml)

```yaml
{
  your
  - config
  - here
}
```

### Your Environment

| software         | version(s)
| ---------------- | -------
| garnet           |  
| node             | 
| npm              | 
| Operating System |

**Comment by Pr0x1m4** [comment]
Project structure has changed, no need for settings file anymore. Closing.
