### ISSUE TITLE
Update server.py /graphs/did/<idx_datapoint> route

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/insite#6]
infoset-ng no longer provides idx_agent values from the iset_datapoint table for a specific idx_datapoint. This idx_agent value now needs to be retrieved using not just the db/datapoint/getidxdatapoint route, but the db/deviceagent/getidxdeviceagent/ route too.

https://github.com/PalisadoesFoundation/infoset-ng/issues/37

**Comment by Pr0x1m4** [comment]
Stale issue, closing.
